server:
  port: 8082
  
spring:
  application:
    name: stock-service

eureka:
  client:
    registerWithEureka: true
    fatchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhsot
