server:
  port: 8081

spring:
  application:
    name: db-service

eureka:
  client:
    registerWithEureka: true
    fatchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhsot